version: '3.8'

services:
  backend:
    build:
      context: ./MathProject.Host.API
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - postgres
    restart: always

  frontend:
    build:
      context: ./MathProject.Client/MathProject.Client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: always

  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: math_proj_admin
      POSTGRES_PASSWORD: sYf7hv
      POSTGRES_DB: math_project_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: