services:
  mathproject.host.api:
    image: mathproject.host.api
    build:
      context: .
      dockerfile: MathProject.Host.API/Dockerfile
    ports:
      - "5000:80"

  mathproject.client:
    image: mathproject.client
    build:
      context: .
      dockerfile: MathProject.Client/MathProject.Client/Dockerfile
    ports:
      - "80:80"
      
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: math_proj_admin
      POSTGRES_PASSWORD: sYf7hv
      POSTGRES_DB: math_project_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: