version: '3.8'

services:
  backend:
    build:
      context: ./MathProject.Host.API
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    restart: always

  frontend:
    build:
      context: ./MathProject.Client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: always