name: Deploy to VDS with Docker Build

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Archive project files
        run: |
          echo "Archiving project..."
          tar -czf myapp.tar.gz --exclude=.git .

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: myapp-archive
          path: myapp.tar.gz

      - name: Download and extract on VDS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VDS_HOST }}
          username: ${{ secrets.VDS_USER }}
          password: ${{ secrets.VDS_PASSWORD }}
          script: |
            echo "Creating workspace..."
            mkdir -p ~/myapp
            cd ~/myapp

            echo "Removing old files..."
            rm -rf app.tar.gz app/

            echo "Receiving new files..."
            cp /tmp/myapp.tar.gz .
            tar -xzf myapp.tar.gz

            echo "Copying compose files..."
            cp ~/myapp/app/docker-compose.yml .

            echo "Building and restarting containers..."
            docker-compose down
            docker-compose up -d --build

            echo "Cleanup..."
            rm -f myapp.tar.gz
