name: Deploy with Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and Push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./Backend
          file: ./Backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/mywebapi:latest

      - name: Build and Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./Frontend
          file: ./Frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/myblazor:latest

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VDS_HOST }}
          username: ${{ secrets.VDS_USER }}
          password: ${{ secrets.VDS_PASSWORD }}
          script: |
            echo "Pulling images..."
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/mywebapi:latest
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/myblazor:latest

            echo "Stopping containers..."
            docker-compose down

            echo "Starting new containers..."
            docker-compose up -d

            echo "Cleanup unused images..."
            docker image prune -af
