name: Deploy to VDS (WORKING VERSION)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create git archive
        run: |
          echo "Creating clean archive..."
          git archive --format=tar.gz -o myapp.tar.gz HEAD

      - name: Check archive exists
        run: |
          if [ -f myapp.tar.gz ]; then
            echo "Archive created successfully."
            ls -la myapp.tar.gz
          else
            echo "ERROR: Archive was NOT created!"
            exit 1
          fi

      - name: Copy via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VDS_HOST }}
          username: ${{ secrets.VDS_USER }}
          password: ${{ secrets.VDS_PASSWORD }}
          port: 22
          source: "myapp.tar.gz"
          target: "/home/${{ secrets.VDS_USER }}/temp-archive.tar.gz"

 - name: Extract and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VDS_HOST }}
          username: ${{ secrets.VDS_USER }}
          password: ${{ secrets.VDS_PASSWORD }}
          script: |
            echo "Cleaning up old files..."
            rm -rf ~/myapp ~/myapp.tar.gz || true
            mkdir -p ~/myapp

            echo "Check if archive exists in /home/root..."
            if [ -f /home/root/temp-archive.tar.gz ]; then
              echo "Archive found. Moving to home directory..."
              mv /home/root/temp-archive.tar.gz ~/temp-archive.tar.gz
            else
              echo "ERROR: Archive not found in /home/root!"
              exit 1
            fi

            echo "Verifying archive..."
            if tar -tzf ~/temp-archive.tar.gz > /dev/null; then
              echo "Archive is valid."
            else
              echo "ERROR: Invalid or corrupted archive!"
              exit 1
            fi

            echo "Extracting files..."
            cd ~/myapp
            tar -xzf ~/temp-archive.tar.gz

            echo "Checking docker-compose.yml..."
            if [ -f docker-compose.yml ]; then
              echo "docker-compose.yml found."
            else
              echo "ERROR: docker-compose.yml NOT FOUND!"
              exit 1
            fi

            echo "Building Docker images..."
            docker-compose down --remove-orphans || true
            docker-compose up -d --build

            echo "Cleanup..."
            rm -f ~/temp-archive.tar.gz
